os: linux
language: ruby
cache:
  bundler: true
services:
  - docker

before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - rails db:create && rails db:migrate && rails db:seed

script:
  - bundle exec rspec spec --format documentation
  - bundle exec rubocop .
  - bundle exec rubycritic --no-browser --minimum-score 90
